name: dudu
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  json_serializable: ^2.0.0
  cached_network_image: ^2.3.0-rc
  shared_preferences: ^0.5.1+1
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^3.0.1
  flutter_webview_plugin: ^0.3.11
  url_launcher: ^5.0.2
  video_player: ^0.10.0+4
  image_picker: ^0.6.6+1
  nav_router:
    path: ../nav_router/
  popup_menu: ^1.0.5
  progress_indicators: ^0.1.5
  photo_view: ^0.9.2
  image_gallery_saver: ^1.2.2
  chewie: ^0.9.10
  path_provider: ^1.6.9
  like_button: ^1.0.1
  flutter_easyrefresh: ^2.1.5
  flutter_datetime_picker: ^1.4.0
  theme_provider: ^0.3.3
  provider: ^4.3.1
  extended_nested_scroll_view: ^1.0.1
  flutter_blurhash: ^0.5.0
  flutter_typeahead: ^1.8.5
  rich_text_controller: ^1.1.0
  flutter_local_notifications: ^1.4.4+2
  intl: ^0.16.1
  flutter_image_compress: ^0.7.0
  package_info: ^0.4.1
  crypto: ^2.1.4
  open_file: ^3.0.1
  pull_to_refresh: ^1.6.1






dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.2
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: "^0.7.3"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - image/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
